### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by BlackMage2** [keisentraut/python-comdirect-api#11]
The script doesn't work.
i have entered correct data but it doesn`t work.

i get only
`Traceback (most recent call last):
  File "/home/user/Development/python-comdirect-api/bin/download_all_documents.py", line 26, in <module>
    s = Session(user, password, client_id, client_secret)
  File "/home/user/.local/lib/python3.10/site-packages/comdirect_api/session.py", line 44, in __init__
    raise RuntimeError(
RuntimeError: POST https://api.comdirect.de/oauth/token returned status 401`

i have tested get_account_balances_and_transactions.py and download_all_documents.py

**Comment by BlackMage2** [comment]
have anyone test it successfull in last time?

i have entered valid auth data in creds.py

**Comment by basslet** [comment]
download_all_documents.py works fine for me

**Comment by keisentraut** [comment]
Sorry, I am bad at maintaining this code. My main use case was downloading all documents but comdirect now supports downloading as ZIP, so it is much simpler to do it in user interface.
Feel free to submit pull requests, if you figure out what exactly the problem is.
