### ISSUE TITLE
Get account balances raises assertion

### ISSUE THREAD

**Issue by basslet** [keisentraut/python-comdirect-api#12]
Installation was successful. Auth works. Downloading all documents works. 

I'm trying to get transactions so that I can save them to csv, because the Comdirect csv export on their website is a real PITA.

When I run get_account_balances_and_transactions.py, I get this assertion that I can't quite figure out. 

(base) MacBookPro:bin dbu$ python get_account_balances_and_transactions.py 
Please press ENTER after confirming push-tan 
Balance of Direct Access Savings-Plus Account (DE962004xxxxxxxxxxxxxx): xxxxx.26 EUR
Recent transactions:
TRANSFER
TRANSFER
TRANSFER
TRANSFER
BANK_FEES
Traceback (most recent call last):
  File "/Users/dbu/Repositories/python-comdirect-api/bin/get_account_balances_and_transactions.py", line 32, in <module>
    transactions = s.account_get_transactions(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbu/miniconda3/lib/python3.11/site-packages/comdirect_api/session.py", line 254, in account_get_transactions
    return [comdirect_api.types.AccountTransaction(i) for i in response.json()["values"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbu/miniconda3/lib/python3.11/site-packages/comdirect_api/session.py", line 254, in <listcomp>
    return [comdirect_api.types.AccountTransaction(i) for i in response.json()["values"]]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbu/miniconda3/lib/python3.11/site-packages/comdirect_api/types.py", line 160, in __init__
    assert(self.transactionType in TransactionType)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by keisentraut** [comment]
Probably comdirect changed something in the JSON reply. I am not really using my own code anymore, so I probably won't fix it. But feel free to support a pull request, I will merge it then.

**Comment by keisentraut** [comment]
might be fixed now. I am not a customer of comdirect anymore, so I cannot test it :)
